import java.util.Iterator;
import model.Category;
import model.Product;
import DatabaseOperation.CategoryDatabaseOperation;
import DatabaseOperation.ProductDatabaseOperation;
import java.util.ArrayList;
/**
 *
 * @author Apsara Madhuwanthi
 */
public class AddNewProduct extends javax.swing.JFrame {

    private Object txtName;

    /**
     * Creates new form AddNewProduct
     */
    public AddNewProduct() {
        initComponents();
        btnSave.setEnabled(false);
    }
    
     public void validateFields(){
        String name = txtName.getText();
        String price = txtPrice.getText();
        if (!name.equals("") && !price.equals(""))
                btnSave.setEnabled(true);
        else
            btnSave.setEnabled(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCategory = new javax.swing.JComboBox<>();
        txtPrice = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        jLabel1.setText("New Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, -1, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(954, 12, 27, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 179, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Category");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 249, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 323, -1, -1));

        txtName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 176, 323, -1));

        txtCategory.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 246, 323, -1));

        txtPrice.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 320, 323, -1));

        btnSave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 424, -1, -1));

        btnClear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 424, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>                        

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {                                    
        validateFields();
    }                                   

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {                                     
      validateFields();
    }                                    

    private void formComponentShown(java.awt.event.ComponentEvent evt) {                                    
                            
        ArrayList<Category> list = CategoryDatabaseOperation.getAllRecords();
        Iterator<Category> itr = list.iterator();
        while (itr.hasNext()) {
            Category categoryObj = itr.next();
            
    }          /**
ABOUT US Page */
body{
	background-color:#232a36;
}

.header{
	position:absolute;
	top:0;
	background-color:#232a36;
	color:white;
	border-bottom:2px solid white;
	width: 100%
}

#square{	
	position:absolute;
	top:10%;
	left:25%;
	right:25%;
	height:85%;
	width:50%;
	background-color:#232a36;
	border:5px solid black;
}

.infoTitle{
	display:block;
	margin-left:auto;
	margin-right:auto;
	margin-top:2%;
	border: 2.4px solid black;
	background-color:white;
	Width: 95%;
	font-size:1.5em;
	font-weight:bold;
}

.info{
	display:block;
	overflow:scroll;
	margin-left:auto;
	margin-right:auto;
	margin-top: 5px;
	border: 2.4px solid black;
	background-color:white;
	Width: 95%;
	height:90%;
	font-size:1.2em;
}

p{
	padding:02%;
}

#footer{
	position:absolute;
	bottom:0;
	right:36%;
	background-color:white;
	border: 2.5px solid black;
	
}

.link{
	color:black;
	font-family:Avenir Book;	
	float:left;
	margin-left:2px;
	margin-right:2px;
;}
.inbetween{
	color:black;
	float:left;
	margin-left:2px;
	margin-right:2px;
}
dabblet.html
<header class="header">Home Button</header>
<body>
<div id="square">
	<div class="infoTitle">About Denim Discovery</div>
	<div class="info">
	<p>Denim Discovery grew out of recognizing the facts of life— Life is hard, so is shopping for jeans. Retail stores and online stores aren’t perfect, neither are you, but that doesn’t mean you don’t deserve a nice pair of jeans.</p>
	<p>This is why the Internet was created. This isn’t a Nordstrom rack jean table, go out a get a pair of jeans that makes girls look and think "Oh yeah."</p>
	</div>
</div>
<div id='footer'>
	<div class="link">About DD</div><div class="inbetween">|</div>
	<div class="link">Our Methodology</div><div class="inbetween">|</div>
	<div class="link">Buying Jeans</div><div class="inbetween">|</div>
	<div class="link">Contact Us</div>
</div>
</body>
    }                                   

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {                                        
        Product product = new Product();
       
        
        
        
        
        ProductDatabaseOperation.save(product);
        setVisible(false);
        new AddNewProduct().setVisible(true);
    }                             